#ifndef RC_MAPONE
#define RC_MAPONE

#include <array>
#include "../ResourceManager.hpp"

std::array<std::array<Textures::WallSpecific, 24>, 18> mapOne = {
    {{Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::Brick, Textures::WallSpecific::Brick,
      Textures::WallSpecific::Brick, Textures::WallSpecific::Brick, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Brick,
      Textures::WallSpecific::Brick, Textures::WallSpecific::Brick, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::Brick, Textures::WallSpecific::Brick,
      Textures::WallSpecific::Brick, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid,      Textures::WallSpecific::None,      Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,      Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,      Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::ChunkOne,  Textures::WallSpecific::ChunkTwo,
      Textures::WallSpecific::ChunkThree, Textures::WallSpecific::ChunkFour, Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,      Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,      Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,      Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid,      Textures::WallSpecific::None,       Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,       Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,       Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::ChunkFive,  Textures::WallSpecific::ChunkSix,
      Textures::WallSpecific::ChunkSeven, Textures::WallSpecific::ChunkEight, Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,       Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,       Textures::WallSpecific::None,
      Textures::WallSpecific::None,       Textures::WallSpecific::None,       Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid,       Textures::WallSpecific::Cracked,     Textures::WallSpecific::Cracked,
      Textures::WallSpecific::Cracked,     Textures::WallSpecific::None,        Textures::WallSpecific::None,
      Textures::WallSpecific::None,        Textures::WallSpecific::None,        Textures::WallSpecific::None,
      Textures::WallSpecific::None,        Textures::WallSpecific::ChunkNine,   Textures::WallSpecific::ChunkTen,
      Textures::WallSpecific::ChunkEleven, Textures::WallSpecific::ChunkTwelve, Textures::WallSpecific::None,
      Textures::WallSpecific::None,        Textures::WallSpecific::None,        Textures::WallSpecific::None,
      Textures::WallSpecific::None,        Textures::WallSpecific::None,        Textures::WallSpecific::Cracked,
      Textures::WallSpecific::Cracked,     Textures::WallSpecific::Cracked,     Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid,         Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::ChunkThirteen, Textures::WallSpecific::ChunkFourteen,
      Textures::WallSpecific::ChunkFifteen,  Textures::WallSpecific::ChunkSixteen,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::None,
      Textures::WallSpecific::None,          Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid,   Textures::WallSpecific::None,    Textures::WallSpecific::None,
      Textures::WallSpecific::None,    Textures::WallSpecific::Cracked, Textures::WallSpecific::Cracked,
      Textures::WallSpecific::Cracked, Textures::WallSpecific::None,    Textures::WallSpecific::None,
      Textures::WallSpecific::None,    Textures::WallSpecific::None,    Textures::WallSpecific::None,
      Textures::WallSpecific::None,    Textures::WallSpecific::None,    Textures::WallSpecific::None,
      Textures::WallSpecific::None,    Textures::WallSpecific::None,    Textures::WallSpecific::Cracked,
      Textures::WallSpecific::Cracked, Textures::WallSpecific::Cracked, Textures::WallSpecific::None,
      Textures::WallSpecific::None,    Textures::WallSpecific::None,    Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::Floor, Textures::WallSpecific::Floor, Textures::WallSpecific::Floor,
      Textures::WallSpecific::Floor, Textures::WallSpecific::Floor, Textures::WallSpecific::Floor,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::Floor, Textures::WallSpecific::Floor,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::Floor, Textures::WallSpecific::Floor,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Floor, Textures::WallSpecific::Floor, Textures::WallSpecific::None,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::Floor, Textures::WallSpecific::Floor, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Floor,
      Textures::WallSpecific::Floor, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Floor,
      Textures::WallSpecific::Floor, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid},
     {Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::None,  Textures::WallSpecific::None,  Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid,
      Textures::WallSpecific::Solid, Textures::WallSpecific::None,  Textures::WallSpecific::None,
      Textures::WallSpecific::Solid, Textures::WallSpecific::Solid, Textures::WallSpecific::Solid}}};

#endif